apiVersion: v1
kind: ReplicationController
metadata: 
      name: rcontroller-nginx
spec:
  replicas: 3
  template:
    metadata:
      name: firstpod1
      labels:
        type: app
    spec:
      containers:
        - image: coolgourav147/nginx-custom
          name: firstpodcontainer
