apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    name: app
spec:
  type: NodePort
  ports:  
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30036
      protocol: TCP
  selector:    
    type: app     